// ignore_for_file: invalid_annotation_target

// GDD v6 — Vex AI Critic Domain Model
// Procedural Vogue-style fashion critique with 4-tier verdict system
// Alabaster Standard: Editorial precision meets psychological impact

import 'package:freezed_annotation/freezed_annotation.dart';

part 'vex_review.freezed.dart';
part 'vex_review.g.dart';

/// Vex verdict tiers — the emotional spectrum of fashion critique
///
/// Tarnished: The design failed to meet basic standards
/// Derivative: Competent but culturally invisible
/// Visionary: Trend-aware with genuine creative merit
/// Sovereign: Transcendent work that defines the era
enum VexVerdict {
  tarnished,
  derivative,
  visionary,
  sovereign,
}

/// Extension for verdict display properties
extension VexVerdictExtension on VexVerdict {
  /// Display name for UI headers
  String get displayName {
    switch (this) {
      case VexVerdict.tarnished:
        return 'TARNISHED';
      case VexVerdict.derivative:
        return 'DERIVATIVE';
      case VexVerdict.visionary:
        return 'VISIONARY';
      case VexVerdict.sovereign:
        return 'SOVEREIGN';
    }
  }

  /// Color indicator for UI styling (Aurelian palette references)
  String get colorToken {
    switch (this) {
      case VexVerdict.tarnished:
        return 'obsidian_tarnish';
      case VexVerdict.derivative:
        return 'grey_muted';
      case VexVerdict.visionary:
        return 'champagne_gold';
      case VexVerdict.sovereign:
        return 'aurelian_radiance';
    }
  }

  /// Whether this verdict includes the rotating Sovereign Seal
  bool get showsSovereignSeal => this == VexVerdict.sovereign;

  /// Whether the player "survived" the critique (not tarnished)
  bool get isSuccessful => this != VexVerdict.tarnished;

  /// Ordinal for sorting/priority
  int get tier {
    switch (this) {
      case VexVerdict.tarnished:
        return 0;
      case VexVerdict.derivative:
        return 1;
      case VexVerdict.visionary:
        return 2;
      case VexVerdict.sovereign:
        return 3;
    }
  }
}

/// A procedural Vex review — editorial critique translated from math
///
/// Generated by VexAIEngine from HypeCalculationResult
/// Displayed in VexReviewCard with Aurelian Standard styling
@freezed
class VexReview with _$VexReview {
  @JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
  const factory VexReview({
    /// Editorial headline — the verdict's thesis statement
    required String headline,

    /// Body copy — the analytical breakdown
    required String body,

    /// The verdict tier — determines UI styling and emotional weight
    required VexVerdict verdict,

    /// Final hype score that generated this review
    required double hypeScore,

    /// The matching tsunami tag (if any) — referenced in critique
    String? matchingTsunamiTag,

    /// Tsunami multiplier applied (1.0 or 1.5)
    double? tsunamiMultiplier,

    /// Whether player opted in to receive this review
    @Default(true) bool wasOptedIn,

    /// Timestamp of generation
    @Default(null) DateTime? generatedAt,
  }) = _VexReview;

  const VexReview._();

  factory VexReview.fromJson(Map<String, Object?> json) =>
      _$VexReviewFromJson(json);

  /// Formatted hype score for display (e.g., "87.5")
  String get hypeScoreFormatted => hypeScore.toStringAsFixed(1);

  /// Multiplier display string (e.g., "1.5x")
  String? get multiplierDisplay =>
      tsunamiMultiplier != null ? '${tsunamiMultiplier}x' : null;

  /// Whether this review references a trend tsunami
  bool get referencesTsunami =>
      matchingTsunamiTag != null && tsunamiMultiplier != null;

  /// The "flex" statement — what players can quote
  String get quotableLine {
    switch (verdict) {
      case VexVerdict.tarnished:
        return 'Vex declined to comment further.';
      case VexVerdict.derivative:
        return 'Competent execution. Forgettable concept.';
      case VexVerdict.visionary:
        return 'This is precisely what the moment demands.';
      case VexVerdict.sovereign:
        return 'You have authored a cultural moment.';
    }
  }

  /// Shareable text for social features
  String get shareableText {
    final StringBuffer buffer = StringBuffer();
    buffer.writeln('VEX CRITIQUE: ${verdict.displayName}');
    buffer.writeln('"$headline"');
    buffer.writeln();
    buffer.writeln(quotableLine);
    if (referencesTsunami) {
      buffer.writeln();
      buffer
          .writeln('Riding the $matchingTsunamiTag wave at $multiplierDisplay');
    }
    return buffer.toString();
  }
}

/// Collection extension for batch operations
extension VexReviewListExtension on List<VexReview> {
  /// Filter to only successful reviews (derivative or better)
  List<VexReview> get successfulOnly =>
      where((VexReview r) => r.verdict.isSuccessful).toList();

  /// Filter to only trend-matched reviews
  List<VexReview> get tsunamiMatchedOnly =>
      where((VexReview r) => r.referencesTsunami).toList();

  /// Sort by hype score descending
  List<VexReview> get byHypeDesc => this
    ..sort((VexReview a, VexReview b) => b.hypeScore.compareTo(a.hypeScore));

  /// Sort by verdict tier descending (sovereign first)
  List<VexReview> get byVerdictTierDesc => this
    ..sort(
      (VexReview a, VexReview b) => b.verdict.tier.compareTo(a.verdict.tier),
    );
}
