// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-5vIMXOhOJo7wLUBK_ds5SXYw-pPoG5w',
    appId: '1:757476640789:web:d36bc4023ba566bc9ca61c',
    messagingSenderId: '757476640789',
    projectId: 'the-styliste',
    authDomain: 'the-styliste.firebaseapp.com',
    storageBucket: 'the-styliste.firebasestorage.app',
    measurementId: 'G-XDQTCW0873',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyVvmLVZcmCRLgKCC2Asz8t2fKfNwrgRw',
    appId: '1:757476640789:android:9d964f93910db59e9ca61c',
    messagingSenderId: '757476640789',
    projectId: 'the-styliste',
    storageBucket: 'the-styliste.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVMnUbvB0wYHZyvFmGyxlTpF8ifDClQLc',
    appId: '1:757476640789:ios:cc385301aec27ed49ca61c',
    messagingSenderId: '757476640789',
    projectId: 'the-styliste',
    storageBucket: 'the-styliste.firebasestorage.app',
    iosBundleId: 'com.skinteethnerds.styliste.theStyliste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVMnUbvB0wYHZyvFmGyxlTpF8ifDClQLc',
    appId: '1:757476640789:ios:528a8e5f0a0f03d89ca61c',
    messagingSenderId: '757476640789',
    projectId: 'the-styliste',
    storageBucket: 'the-styliste.firebasestorage.app',
    iosBundleId: 'o',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-5vIMXOhOJo7wLUBK_ds5SXYw-pPoG5w',
    appId: '1:757476640789:web:f645baeaedd1dc1f9ca61c',
    messagingSenderId: '757476640789',
    projectId: 'the-styliste',
    authDomain: 'the-styliste.firebaseapp.com',
    storageBucket: 'the-styliste.firebasestorage.app',
    measurementId: 'G-ETSWM4ZRWP',
  );
}
