ALTER TABLE public.player_roster
  ADD COLUMN IF NOT EXISTS stamina INTEGER NOT NULL DEFAULT 100 CHECK (stamina BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS morale INTEGER NOT NULL DEFAULT 100 CHECK (morale BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS last_stamina_refresh TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS gala_cooldown_until TIMESTAMPTZ;
